---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    proxmox:
      hosts:
        proxmox_host:
          ansible_host: "{{ proxmox_api_host }}"
          ansible_user: root
          ansible_ssh_private_key_file: "{{ proxmox_ssh_key }}"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"
          ansible_python_interpreter: /usr/bin/python3
