#!/usr/bin/env bash
# scripts/status.sh — show the status of all clusters managed by this repo
#
# Usage:
#   ./scripts/status.sh              # status of all clusters found in tmp/
#   ./scripts/status.sh hub dr1      # status of specific clusters only
#
# Requires:
#   - proxmox.yml (for infra_ip)
#   - tmp/<cluster>/auth/kubeconfig  (generated by make install)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
OC="$REPO_DIR/tmp/tools/$(grep 'ocp_version' "$REPO_DIR/overrides.yml" 2>/dev/null | awk '{print $2}' | tr -d '"' | head -1)/oc"
[ ! -x "$OC" ] && OC=$(command -v oc 2>/dev/null || echo "")

INFRA_IP=$(grep 'infra_ip:' "$REPO_DIR/proxmox.yml" 2>/dev/null | awk '{print $2}' | head -1)
SSH_KEY=$(grep 'proxmox_ssh_key' "$REPO_DIR/proxmox.yml" 2>/dev/null | sed "s|.*expanduser('||;s|'.*||;s|~|$HOME|" | head -1)
[ -z "$SSH_KEY" ] && SSH_KEY="$HOME/.ssh/id_pxe_debug"

# Colour codes
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

# Determine which clusters to show
if [ "$#" -gt 0 ]; then
    CLUSTERS=("$@")
else
    CLUSTERS=()
    for d in "$REPO_DIR/tmp"/*/; do
        name=$(basename "$d")
        [[ "$name" == "tools" ]] && continue
        [ -f "$d/auth/kubeconfig" ] && CLUSTERS+=("$name")
    done
fi

if [ "${#CLUSTERS[@]}" -eq 0 ]; then
    echo "No clusters found in tmp/ — run 'make install' first"
    exit 0
fi

echo ""
printf "${BOLD}%-12s %-8s %-22s %-12s %-10s %s${RESET}\n" \
    "CLUSTER" "NODE" "VERSION" "OPERATORS" "CVO%" "STATUS"
printf '%0.s─' {1..90}; echo ""

for cluster in "${CLUSTERS[@]}"; do
    KC="$REPO_DIR/tmp/$cluster/auth/kubeconfig"
    [ ! -f "$KC" ] && printf "${RED}%-12s kubeconfig not found${RESET}\n" "$cluster" && continue

    # Run oc commands — try direct first, fall back to via infra VM
    run_oc() {
        KUBECONFIG="$KC" "$OC" "$@" 2>/dev/null
    }

    if [ -z "$OC" ] || ! run_oc version --client &>/dev/null; then
        # Fallback: run via infra VM where local.lab DNS resolves
        run_oc() {
            scp -i "$SSH_KEY" -o StrictHostKeyChecking=no -o LogLevel=ERROR \
                "$KC" "rocky@${INFRA_IP}:/tmp/${cluster}-status-kc" &>/dev/null
            ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o LogLevel=ERROR \
                "rocky@${INFRA_IP}" \
                "KUBECONFIG=/tmp/${cluster}-status-kc /usr/local/bin/oc $* 2>/dev/null" 2>/dev/null
        }
    fi

    # Gather data
    NODE_LINE=$(run_oc get nodes --no-headers 2>/dev/null | head -1)
    NODE_NAME=$(echo "$NODE_LINE" | awk '{print $1}')
    NODE_STATUS=$(echo "$NODE_LINE" | awk '{print $2}')
    OCP_VER=$(echo "$NODE_LINE" | awk '{print $5}')

    CVO_LINE=$(run_oc get clusterversion version --no-headers 2>/dev/null | head -1)
    CVO_AVAIL=$(echo "$CVO_LINE" | awk '{print $3}')   # True/False
    CVO_PROG=$(echo "$CVO_LINE" | awk '{print $4}')    # True/False
    CVO_MSG=$(run_oc get clusterversion version \
        -o jsonpath='{.status.conditions[?(@.type=="Progressing")].message}' 2>/dev/null || true)
    CVO_STATUS=$(echo "$CVO_MSG" | grep -oE '[0-9]+ of [0-9]+ done \([0-9]+%' | head -1 || true)
    if [ -z "$CVO_STATUS" ] && [ -n "$CVO_MSG" ]; then
        if echo "$CVO_MSG" | grep -qiE "MultipleErrors|not available"; then
            CVO_STATUS="progressing"
        else
            CVO_STATUS=$(echo "$CVO_MSG" | sed 's/Unable to apply [^:]*: //;s/Error while reconciling [^:]*: //' | cut -c1-40)
        fi
    fi

    CO_TOTAL=$(run_oc get co --no-headers 2>/dev/null | wc -l | tr -d ' ')
    CO_OK=$(run_oc get co --no-headers 2>/dev/null | grep -c 'True.*False.*False' 2>/dev/null || echo 0)
    CO_STUCK=$(run_oc get co --no-headers 2>/dev/null \
        | grep -v 'True.*False.*False' \
        | grep -v '^$' \
        | awk '{print $1}' \
        | tr '\n' ',' | sed 's/,$//' || true)

    # Colour node status
    if [ "$NODE_STATUS" = "Ready" ]; then
        NODE_COL="${GREEN}${NODE_STATUS}${RESET}"
    elif [ -n "$NODE_STATUS" ]; then
        NODE_COL="${YELLOW}${NODE_STATUS}${RESET}"
    else
        NODE_COL="${RED}unreachable${RESET}"
    fi

    # Colour operators
    if [ "$CO_OK" = "$CO_TOTAL" ] && [ "$CO_TOTAL" -gt 0 ]; then
        OP_COL="${GREEN}${CO_OK}/${CO_TOTAL}${RESET}"
    else
        OP_COL="${YELLOW}${CO_OK}/${CO_TOTAL}${RESET}"
    fi

    # Overall status — use oc get clusterversion specifically for Available condition
    CVO_COMPLETE=$(run_oc get clusterversion version \
        -o jsonpath='{.status.conditions[?(@.type=="Available")].status}' 2>/dev/null)
    if [ "$CVO_COMPLETE" = "True" ]; then
        STATUS="${GREEN}Complete ✓${RESET}"
    elif [ -n "$NODE_STATUS" ]; then
        STATUS="${YELLOW}Installing...${RESET}"
    else
        STATUS="${RED}Bootstrapping${RESET}"
    fi

    printf "${CYAN}%-12s${RESET} %-8s %-22s " "$cluster" "$NODE_STATUS" "${OCP_VER:-—}"
    printf "%s %-10s " "$(printf "${OP_COL}")" "${CVO_STATUS:----}"
    printf "%s\n" "$(printf "${STATUS}")"

    # Show stuck operators if any
    if [ -n "$CO_STUCK" ] && [ "${CVO_AVAIL:-}" != "True" ]; then
        printf "             ${YELLOW}↳ waiting: %s${RESET}\n" "$CO_STUCK"
    fi
done

echo ""

# VMs summary from proxmox
PROXMOX_HOST=$(grep 'proxmox_api_host:' "$REPO_DIR/proxmox.yml" 2>/dev/null | awk '{print $2}' | head -1)
if [ -n "$PROXMOX_HOST" ] && ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=3 \
    -o LogLevel=ERROR "root@${PROXMOX_HOST}" true &>/dev/null 2>&1; then
    echo "VMs on Proxmox:"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o LogLevel=ERROR \
        "root@${PROXMOX_HOST}" "qm list" 2>/dev/null \
        | grep -v 'stopped\|csi-test\|VMID' \
        | awk '{printf "  %-6s %-25s %s\n", $1, $2, $3}'
    echo ""
fi
